SELECT STUDENTS.FIRST_NAME,
  STUDENTS.LAST_NAME,
  STUDENTS.STUDENT_NUMBER,
  STUDENTS.ENROLL_STATUS,
  STUDENTS.GRADE_LEVEL,
  STUDENTTESTSCORE.NUMSCORE,
  TESTSCORE.NAME,
  TEST.TEST_TYPE,
  TEST.NAME             AS Name1,
  TESTSCORE.DESCRIPTION AS DESCRIPTION1,
  TESTSCORE.TESTID,
  PS.STOREDGRADES.EARNEDCRHRS


FROM STUDENTS
INNER JOIN STUDENTTESTSCORE
ON STUDENTS.ID = STUDENTTESTSCORE.STUDENTID
INNER JOIN STUDENTTEST
ON STUDENTTEST.ID = STUDENTTESTSCORE.STUDENTTESTID
INNER JOIN TESTSCORE
ON TESTSCORE.ID = STUDENTTESTSCORE.TESTSCOREID
INNER JOIN TEST
ON TEST.ID = TESTSCORE.TESTID
INNER JOIN PS.STOREDGRADES
ON PS.STOREDGRADES.STUDENTID = STUDENTS.ID


WHERE STUDENTS.ENROLL_STATUS = 0
AND STUDENTTEST.SCHOOLID     = 100
AND STUDENTTEST.GRADE_LEVEL  = 12