SELECT COUNT(*),
  ps.cc.EXPRESSION,
  (SELECT t.PREFERREDNAME FROM teachers t WHERE t.ID = ps.cc.TEACHERID
  ) Teacher
FROM ps.cc
INNER JOIN PS.STUDENTS
ON ps.cc.STUDENTID   = PS.STUDENTS.ID
WHERE ps.cc.SCHOOLID = 100
AND ps.cc.TERMID    IN (2800, 2802)
AND ps.cc.EXPRESSION = '10(A)'
GROUP BY ps.cc.EXPRESSION,
  ps.cc.COURSE_NUMBER
  || '.'
  || ps.cc.SECTION_NUMBER,
  ps.cc.TEACHERID
ORDER BY Teacher