SELECT PS.STUDENTS.STUDENT_NUMBER,
  PS.STUDENTS.LASTFIRST,
  PS.STUDENTS.LAST_NAME,
  PS.STUDENTS.FIRST_NAME,
  PS.STUDENTS.GRADE_LEVEL,
  PS.CC.COURSE_NUMBER,
  TEACHERS.LASTFIRST AS TEACHERNAME,
  PS.S_SC_STU_X.PLAN504CODE,
  PS.COURSES.COURSE_NAME,
  PS.STUDENTS.LUNCHSTATUS
FROM PS.STUDENTS
INNER JOIN PS.CC
ON PS.STUDENTS.ID = PS.CC.STUDENTID
INNER JOIN SECTIONS
ON SECTIONS.ID = PS.CC.SECTIONID
INNER JOIN TEACHERS
ON TEACHERS.ID = SECTIONS.TEACHER
INNER JOIN PS.COURSES
ON PS.COURSES.COURSE_NUMBER = SECTIONS.COURSE_NUMBER
INNER JOIN PS.S_SC_STU_X
ON PS.S_SC_STU_X.STUDENTSDCID   = PS.STUDENTS.DCID
WHERE PS.STUDENTS.ENROLL_STATUS = 0
AND PS.CC.TERMID LIKE '28%'
AND PS.STUDENTS.SCHOOLID = 100
AND (PS.COURSES.COURSE_NUMBER LIKE '%AW'
OR PS.COURSES.COURSE_NUMBER LIKE '%AH')