AP Testing Data
SELECT
S.STUDENT_NUMBER,
S.LASTFIRST,
S.GRADE_LEVEL,
S.LunchStatus,

CC.COURSE_NUMBER,
C.COURSE_NAME,
T.LASTFIRST,
CC.EXPRESSION,
CC.TERMID

FROM
STUDENTS S,
CC,
COURSES C,
TEACHERS T,
SECTIONS SE,
s_sc_stu_x

WHERE
S.ID=CC.STUDENTID
AND SE.ID=CC.SECTIONID
AND T.ID=SE.TEACHER
AND C.COURSE_NUMBER=SE.COURSE_NUMBER
AND --(C.COURSE_NUMBER LIKE '%AW' OR C.COURSE_NUMBER LIKE '%AH')    
AND S.GRADE_LEVEL >8
AND CC.SCHOOLID=100
AND CC.TERMID LIKE '27%'


