SELECT S.STUDENT_NUMBER,
  S.GRADE_LEVEL,
  S.LAST_NAME,
  S.FIRST_NAME,
  G.GPA,
  PS.CC.EXPRESSION,
  PS.SECTIONS.TEACHER,
  (SELECT t.PREFERREDNAME FROM teachers t WHERE t.ID = PS.SECTIONS.TEACHER
  ) Teacher,
  PS.CC.TERMID
FROM Students S
INNER JOIN
  (SELECT SG.STUDENTID,
    TRUNC((SUM(SG.GPA_POINTS * SG.POTENTIALCRHRS) / SUM(SG.POTENTIALCRHRS)), 3) GPA
  FROM StoredGrades SG
  WHERE SG.STORECODE     = 'F1'
  AND SG.POTENTIALCRHRS  > 0
  AND SG.EXCLUDEFROMGPA <> 1
  GROUP BY SG.STUDENTID
  ) G
ON S.ID = G.STUDENTID
INNER JOIN PS.CC
ON PS.CC.STUDENTID = S.ID
INNER JOIN PS.SECTIONS
ON PS.CC.SECTIONID   = PS.SECTIONS.ID
WHERE S.GRADE_LEVEL  < 12
AND S.GRADE_LEVEL   IN ('9', '10', '11')
AND G.GPA            > 2.9
AND PS.CC.EXPRESSION = '10(A)'
AND PS.CC.TERMID LIKE '28%'
AND S.ENROLL_STATUS = 0
AND S.SCHOOLID      = 100
ORDER BY G.GPA DESC