SELECT students.LASTFIRST,
  TO_CHAR(students.STUDENT_NUMBER),
  PS.SECTIONS.COURSE_NUMBER,
  PS.SECTIONS.TERMID,
  PS.COURSES.COURSE_NAME
FROM students
INNER JOIN PS.CC
ON PS.CC.STUDENTID = students.ID
INNER JOIN PS.SECTIONS
ON PS.SECTIONS.ID = PS.CC.SECTIONID
INNER JOIN PS.COURSES
ON PS.COURSES.COURSE_NUMBER = PS.SECTIONS.COURSE_NUMBER
WHERE PS.SECTIONS.COURSE_NUMBER LIKE '322100%'
AND PS.SECTIONS.TERMID = 2802
AND students.SCHOOLID      = 100
AND students.ENROLL_STATUS = 0
ORDER BY students.LASTFIRST