SELECT
  (SELECT SCHOOLS.ABBREVIATION
  FROM SCHOOLS
  WHERE STUDENTS.SCHOOLID = SCHOOLS.SCHOOL_NUMBER
  ) AS SCHOOL,
  TO_CHAR(STUDENTS.STUDENT_NUMBER),
  STUDENTS.LASTFIRST,
  STOREDGRADES.STORECODE,
  STOREDGRADES.GRADE,
  STOREDGRADES.PERCENT,
  STOREDGRADES.COURSE_NAME,
  STOREDGRADES.TERMID,
  STOREDGRADES.POTENTIALCRHRS,
  STOREDGRADES.EARNEDCRHRS
FROM STUDENTS
INNER JOIN STOREDGRADES
ON STOREDGRADES.STUDENTID       = STUDENTS.ID
WHERE STOREDGRADES.STORECODE    = 'F1'
AND STOREDGRADES.GRADE         IS NULL
AND STOREDGRADES.PERCENT IS NULL
AND STOREDGRADES.POTENTIALCRHRS > 0
AND STUDENTS.GRADE_LEVEL        < 13
ORDER BY 
  STUDENTS.LASTFIRST