SELECT STUDENTS.STUDENT_NUMBER,
  STUDENTS.LASTFIRST AS Name,
  PS.CC.COURSE_NUMBER,
  PS.CC.SECTION_NUMBER,
  PS.CC.EXPRESSION,
  STUDENTS.SCHOOLID,
  PS.CC.TERMID,
  STUDENTS.ENROLL_STATUS
FROM STUDENTS
INNER JOIN PS.CC
ON STUDENTS.ID             = PS.CC.STUDENTID
WHERE STUDENTS.SCHOOLID    = 69
AND PS.CC.TERMID           = 3000
AND STUDENTS.ENROLL_STATUS < 1
ORDER BY Name