SELECT
   students.dcid, 
   (select ABBREVIATION from SCHOOLS where students.SCHOOLID=SCHOOL_NUMBER),
   students.student_number, 
   CHR(60) || 'a href=/admin/students/state/usa_sc/SC_Student_Contacts.html?frn=' || '001' || DCID || ' target=_blank'  || CHR(62) || students.lastfirst || CHR(60) || '/a'  || CHR(62),
    CASE 
        WHEN s_sc_stu_contacts_x.cnt1_cphone not like '___-___-____'
            THEN 'Contact 1 Cell' 
        WHEN s_sc_stu_contacts_x.cnt2_cphone not like '___-___-____'
            THEN 'Contact 2 Cell'  
        WHEN s_sc_stu_contacts_x.cnt3_cphone not like '___-___-____'
            THEN 'Contact 3 Cell'  
        WHEN s_sc_stu_contacts_x.cnt4_cphone not like '___-___-____'
            THEN 'Contact 4 Cell'  
        WHEN s_sc_stu_contacts_x.cnt5_cphone not like '___-___-____'
            THEN 'Contact 5 Cell'  
        WHEN s_sc_stu_contacts_x.cnt6_cphone not like '___-___-____'
            THEN 'Contact 6 Cell'  
        WHEN s_sc_stu_contacts_x.cnt7_cphone not like '___-___-____'
            THEN 'Contact 7 Cell'  
        WHEN s_sc_stu_contacts_x.cnt8_cphone not like '___-___-____'
            THEN 'Contact 8 Cell'  
        WHEN s_sc_stu_contacts_x.cnt9_cphone not like '___-___-____'
            THEN 'Contact 9 Cell'  
        WHEN s_sc_stu_contacts_x.cnt10_cphone not like '___-___-____'
            THEN 'Contact 10 Cell'
        WHEN s_sc_stu_contacts_x.cnt1_hphone not like '___-___-____'
            THEN 'Contact 1 Home' 
        WHEN s_sc_stu_contacts_x.cnt2_hphone not like '___-___-____'
            THEN 'Contact 2 Home'  
        WHEN s_sc_stu_contacts_x.cnt3_hphone not like '___-___-____'
            THEN 'Contact 3 Home'  
        WHEN s_sc_stu_contacts_x.cnt4_hphone not like '___-___-____'
            THEN 'Contact 4 Home'  
        WHEN s_sc_stu_contacts_x.cnt5_hphone not like '___-___-____'
            THEN 'Contact 5 Home'  
        WHEN s_sc_stu_contacts_x.cnt6_hphone not like '___-___-____'
            THEN 'Contact 6 Home'  
        WHEN s_sc_stu_contacts_x.cnt7_hphone not like '___-___-____'
            THEN 'Contact 7 Home'  
        WHEN s_sc_stu_contacts_x.cnt8_hphone not like '___-___-____'
            THEN 'Contact 8 Home'  
        WHEN s_sc_stu_contacts_x.cnt9_hphone not like '___-___-____'
            THEN 'Contact 9 Home'  
        WHEN s_sc_stu_contacts_x.cnt10_hphone not like '___-___-____'
            THEN 'Contact 10 Home'
        WHEN s_sc_stu_contacts_x.cnt1_wphone not like '___-___-____' AND s_sc_stu_contacts_x.cnt1_wphone not like '___-___-____ (%)'
            THEN 'Contact 1 Work' 
        WHEN s_sc_stu_contacts_x.cnt2_wphone not like '___-___-____' AND s_sc_stu_contacts_x.cnt2_wphone not like '___-___-____ (%)'
            THEN 'Contact 2 Work'  
        WHEN s_sc_stu_contacts_x.cnt3_wphone not like '___-___-____' AND s_sc_stu_contacts_x.cnt3_wphone not like '___-___-____ (%)'
            THEN 'Contact 3 Work'  
        WHEN s_sc_stu_contacts_x.cnt4_wphone not like '___-___-____' AND s_sc_stu_contacts_x.cnt4_wphone not like '___-___-____ (%)'
            THEN 'Contact 4 Work'  
        WHEN s_sc_stu_contacts_x.cnt5_wphone not like '___-___-____' AND s_sc_stu_contacts_x.cnt5_wphone not like '___-___-____ (%)'
            THEN 'Contact 5 Work'  
        WHEN s_sc_stu_contacts_x.cnt6_wphone not like '___-___-____' AND s_sc_stu_contacts_x.cnt6_wphone not like '___-___-____ (%)'
            THEN 'Contact 6 Work'  
        WHEN s_sc_stu_contacts_x.cnt7_wphone not like '___-___-____' AND s_sc_stu_contacts_x.cnt7_wphone not like '___-___-____ (%)'
            THEN 'Contact 7 Work'  
        WHEN s_sc_stu_contacts_x.cnt8_wphone not like '___-___-____' AND s_sc_stu_contacts_x.cnt8_wphone not like '___-___-____ (%)'
            THEN 'Contact 8 Work'  
        WHEN s_sc_stu_contacts_x.cnt9_wphone not like '___-___-____' AND s_sc_stu_contacts_x.cnt9_wphone not like '___-___-____ (%)'
            THEN 'Contact 9 Work'  
        WHEN s_sc_stu_contacts_x.cnt10_wphone not like '___-___-____' AND s_sc_stu_contacts_x.cnt10_wphone not like '___-___-____ (%)'
            THEN 'Contact 10 Work'
    END contact 
FROM s_sc_stu_contacts_x INNER JOIN students ON s_sc_stu_contacts_x.studentsdcid = students.dcid 
WHERE 
    CASE 
        WHEN s_sc_stu_contacts_x.cnt1_cphone not like '___-___-____'
            THEN 'Contact 1 Cell' 
        WHEN s_sc_stu_contacts_x.cnt2_cphone not like '___-___-____'
            THEN 'Contact 2 Cell'  
        WHEN s_sc_stu_contacts_x.cnt3_cphone not like '___-___-____'
            THEN 'Contact 3 Cell'  
        WHEN s_sc_stu_contacts_x.cnt4_cphone not like '___-___-____'
            THEN 'Contact 4 Cell'  
        WHEN s_sc_stu_contacts_x.cnt5_cphone not like '___-___-____'
            THEN 'Contact 5 Cell'  
        WHEN s_sc_stu_contacts_x.cnt6_cphone not like '___-___-____'
            THEN 'Contact 6 Cell'  
        WHEN s_sc_stu_contacts_x.cnt7_cphone not like '___-___-____'
            THEN 'Contact 7 Cell'  
        WHEN s_sc_stu_contacts_x.cnt8_cphone not like '___-___-____'
            THEN 'Contact 8 Cell'  
        WHEN s_sc_stu_contacts_x.cnt9_cphone not like '___-___-____'
            THEN 'Contact 9 Cell'  
        WHEN s_sc_stu_contacts_x.cnt10_cphone not like '___-___-____'
            THEN 'Contact 10 Cell'
        WHEN s_sc_stu_contacts_x.cnt1_hphone not like '___-___-____'
            THEN 'Contact 1 Home' 
        WHEN s_sc_stu_contacts_x.cnt2_hphone not like '___-___-____'
            THEN 'Contact 2 Home'  
        WHEN s_sc_stu_contacts_x.cnt3_hphone not like '___-___-____'
            THEN 'Contact 3 Home'  
        WHEN s_sc_stu_contacts_x.cnt4_hphone not like '___-___-____'
            THEN 'Contact 4 Home'  
        WHEN s_sc_stu_contacts_x.cnt5_hphone not like '___-___-____'
            THEN 'Contact 5 Home'  
        WHEN s_sc_stu_contacts_x.cnt6_hphone not like '___-___-____'
            THEN 'Contact 6 Home'  
        WHEN s_sc_stu_contacts_x.cnt7_hphone not like '___-___-____'
            THEN 'Contact 7 Home'  
        WHEN s_sc_stu_contacts_x.cnt8_hphone not like '___-___-____'
            THEN 'Contact 8 Home'  
        WHEN s_sc_stu_contacts_x.cnt9_hphone not like '___-___-____'
            THEN 'Contact 9 Home'  
        WHEN s_sc_stu_contacts_x.cnt10_hphone not like '___-___-____'
            THEN 'Contact 10 Home'
        WHEN s_sc_stu_contacts_x.cnt1_wphone not like '___-___-____' AND s_sc_stu_contacts_x.cnt1_wphone not like '___-___-____ (%)'
            THEN 'Contact 1 Work' 
        WHEN s_sc_stu_contacts_x.cnt2_wphone not like '___-___-____' AND s_sc_stu_contacts_x.cnt2_wphone not like '___-___-____ (%)'
            THEN 'Contact 2 Work'  
        WHEN s_sc_stu_contacts_x.cnt3_wphone not like '___-___-____' AND s_sc_stu_contacts_x.cnt3_wphone not like '___-___-____ (%)'
            THEN 'Contact 3 Work'  
        WHEN s_sc_stu_contacts_x.cnt4_wphone not like '___-___-____' AND s_sc_stu_contacts_x.cnt4_wphone not like '___-___-____ (%)'
            THEN 'Contact 4 Work'  
        WHEN s_sc_stu_contacts_x.cnt5_wphone not like '___-___-____' AND s_sc_stu_contacts_x.cnt5_wphone not like '___-___-____ (%)'
            THEN 'Contact 5 Work'  
        WHEN s_sc_stu_contacts_x.cnt6_wphone not like '___-___-____' AND s_sc_stu_contacts_x.cnt6_wphone not like '___-___-____ (%)'
            THEN 'Contact 6 Work'  
        WHEN s_sc_stu_contacts_x.cnt7_wphone not like '___-___-____' AND s_sc_stu_contacts_x.cnt7_wphone not like '___-___-____ (%)'
            THEN 'Contact 7 Work'  
        WHEN s_sc_stu_contacts_x.cnt8_wphone not like '___-___-____' AND s_sc_stu_contacts_x.cnt8_wphone not like '___-___-____ (%)'
            THEN 'Contact 8 Work'  
        WHEN s_sc_stu_contacts_x.cnt9_wphone not like '___-___-____' AND s_sc_stu_contacts_x.cnt9_wphone not like '___-___-____ (%)'
            THEN 'Contact 9 Work'  
        WHEN s_sc_stu_contacts_x.cnt10_wphone not like '___-___-____' AND s_sc_stu_contacts_x.cnt10_wphone not like '___-___-____ (%)'
            THEN 'Contact 10 Work'
    END IS NOT NULL 
AND students.schoolid <> '999999' 
AND students.grade_level <> 13 AND students.enroll_status IN (0, -1)
AND students.SchoolID =
  Decode(~(curSchoolID),0,students.SCHOOLID,~(curSchoolID))
ORDER BY students.lastfirst