SELECT COUNT(*),
    S_SC_STU_X.ADVISOR
FROM students
INNER JOIN S_SC_STU_X
ON S_SC_STU_X.STUDENTSDCID = students.DCID
WHERE students.SCHOOLID    = 100
AND students.ENROLL_STATUS = 0
GROUP BY ROLLUP(S_SC_STU_X.ADVISOR)