SELECT S.LASTFIRST,
  G.COURSE_NAME,
  G.GRADE,
  TO_CHAR(S.STUDENT_NUMBER)
FROM STUDENTS S
INNER JOIN STOREDGRADES G
ON S.ID = G.STUDENTID
INNER JOIN PS.S_SC_STU_X
ON PS.S_SC_STU_X.STUDENTSDCID = S.DCID
WHERE G.STORECODE             = 'F1'
AND G.SCHOOLID                = 100
AND S.ENROLL_STATUS           = 0
AND G.COURSE_NUMBER LIKE '30%'