SELECT COUNT(*),
  (SELECT t.PREFERREDNAME FROM teachers t WHERE t.ID = ps.cc.TEACHERID
  ) Teacher,
  ps.cc.COURSE_NUMBER
  || '.'
  || ps.cc.SECTION_NUMBER Class,
  PS.STUDENTS.FIRST_NAME AS FIRST_NAME1,
  PS.STUDENTS.LAST_NAME  AS LAST_NAME1,
  PS.COURSES.COURSE_NAME AS COURSE_NAME2
FROM ps.cc
INNER JOIN PS.STUDENTS
ON PS.STUDENTS.ID = ps.cc.STUDENTID
INNER JOIN PS.COURSES
ON ps.cc.COURSE_NUMBER = PS.COURSES.COURSE_NUMBER,
  PS.SECTIONS
WHERE PS.COURSES.COURSE_NAME LIKE '%Intermediate Alg%'
AND ps.cc.SCHOOLID = 100
AND ps.cc.TERMID  IN (2600, 2601)
GROUP BY ps.cc.COURSE_NUMBER
  || '.'
  || ps.cc.SECTION_NUMBER,
  PS.STUDENTS.FIRST_NAME,
  PS.STUDENTS.LAST_NAME,
  PS.COURSES.COURSE_NAME,
  ps.cc.TEACHERID