SELECT students.LASTFIRST,
  students.STUDENT_NUMBER,
  STOREDGRADES.STORECODE,
  STOREDGRADES.GRADE,
  STOREDGRADES.COURSE_NUMBER,
  STOREDGRADES.TEACHER_NAME,
  PS.SECTIONS.EXPRESSION
FROM students
INNER JOIN STOREDGRADES
ON STOREDGRADES.STUDENTID = students.ID
INNER JOIN PS.SECTIONS
ON STOREDGRADES.SECTIONID      = PS.SECTIONS.ID
WHERE STOREDGRADES.STORECODE   = 'S1'
AND STOREDGRADES.GRADE         < 60
AND STOREDGRADES.COURSE_NUMBER = '411600CW'
AND STOREDGRADES.SCHOOLID      = 100
AND students.ENROLL_STATUS     = 0
AND STOREDGRADES.TERMID        = 2801