SELECT S.LASTFIRST,
  G.COURSE_NAME,
  G.GRADE,
  PS.S_SC_STU_X.ADVISOR,
  S.STUDENT_NUMBER
FROM STUDENTS S
INNER JOIN STOREDGRADES G
ON S.ID = G.STUDENTID
INNER JOIN PS.S_SC_STU_X
ON PS.S_SC_STU_X.STUDENTSDCID = S.DCID
WHERE G.SCHOOLID              = 100
AND S.ENROLL_STATUS           = 0
AND G.TERMID LIKE '26%'
AND G.STORECODE           = 'Q1'
AND PS.S_SC_STU_X.ADVISOR = 'Ford, J'