SELECT students.LASTFIRST,
  students.STATE_STUDENTNUMBER,
  S_SC_STU_X.GRADDATE,
  S_SC_STU_X.DIPLOMA_TYPE,
  S_SC_STU_X.DIPLOMAEARNCODE,
  S_SC_STU_X.SCHOOLRES
FROM students
INNER JOIN S_SC_STU_X
ON S_SC_STU_X.STUDENTSDCID = students.DCID
WHERE S_SC_STU_X.GRADDATE  = '07-JUN-18'
AND students.GRADE_LEVEL   = 99
and S_SC_STU_X.SCHOOLRES = '4002100'