SELECT S.STUDENT_NUMBER,
  S.LASTFIRST,
  S.GRADE_LEVEL,
  S.HOME_ROOM,
  E.EXPRESSION,
  (
  CASE SUBSTR(E.TERMID, 4)
    WHEN '0'
    THEN 'Yr'
    WHEN '1'
    THEN 'S1'
    WHEN '2'
    THEN 'S2'
    WHEN '3'
    THEN 'Q1'
    WHEN '4'
    THEN 'Q2'
    WHEN '5'
    THEN 'Q3'
    WHEN '6'
    THEN 'Q4'
  END) AS Term,
  G.GRADE,
  G.PERCENT,
  E.COURSE_NUMBER
  || '.'
  || E.SECTION_NUMBER,
  C.COURSE_NAME,
  (SELECT T.PREFERREDNAME FROM TEACHERS T WHERE T.ID = E.TEACHER
  ) AS Teacher
FROM STUDENTS S
INNER JOIN PGFINALGRADES G
ON S.ID = G.STUDENTID
INNER JOIN SECTIONS E
ON E.ID = G.SECTIONID
INNER JOIN COURSES C
ON C.COURSE_NUMBER = E.COURSE_NUMBER
WHERE G.PERCENT    < 80
AND G.PERCENT      > 69
AND E.TERMID LIKE '3%'
AND E.SCHOOLID       = 100
AND G.FINALGRADENAME = 'Q1'
AND S.ENROLL_STATUS  = 0
ORDER BY S.LASTFIRST,
  E.EXPRESSION