--symbols in doctor_name field 
SELECT (select ABBREVIATION from SCHOOLS where students.SCHOOLID=SCHOOL_NUMBER) as School, 'Doctor Name' as "Error Location", 'Symbols in doctor name' as Error, students.LASTFIRST, to_char(students.STUDENT_NUMBER) as Student_Number, students.DOCTOR_NAME FROM students Where Enroll_Status in (0,-1) and students.DOCTOR_NAME is not null and students.DOCTOR_NAME like '%"%' and schoolid not in (999999, 43) and grade_level <> 13 and Enroll_Status = 0;

--doctor phn
select (select ABBREVIATION from SCHOOLS where students.SCHOOLID=SCHOOL_NUMBER) as School, 'Doctor Phone' as "Error Location", 'Symbols in doctor phone' as Error, students.LASTFIRST, to_char(students.STUDENT_NUMBER) as Student_Number, doctor_phone from students where doctor_phone not like '___-___-____' and schoolid not in (999999, 43) and grade_level <> 13 and Enroll_Status = 0;

--medicaid number contains letters
SELECT (select ABBREVIATION from SCHOOLS where students.SCHOOLID=SCHOOL_NUMBER) as School, 'Medicaid Number' as "Error Location", 'Letters in Medicaid number' as Error, students.LASTFIRST, to_char(students.STUDENT_NUMBER) as Student_Number, /*translate numbers to blanks then trim the blanks*/ TRIM(TRANSLATE(s_sc_stu_x.medicaidid, '0123456789','          ')) FROM s_sc_stu_x, students where s_sc_stu_x.studentsdcid = students.dcid AND TRIM(TRANSLATE(s_sc_stu_x.medicaidid, '0123456789','          ')) is not null and schoolid <> '999999' and grade_level <> 13 and Enroll_Status in (0,-1);

 --Parent name blank, relationship not blank
select  (select ABBREVIATION from SCHOOLS where students.SCHOOLID=SCHOOL_NUMBER) as School, 'Contact 1' as "Error Location", 'Parent name field blank' as Error, students.LASTFIRST, students.STUDENT_NUMBER, cnt1_rel, cnt1_fname, cnt1_lname from  s_sc_stu_contacts_x inner join students on s_sc_stu_contacts_x.studentsdcid=students.dcid where cnt1_rel is not null and (cnt1_lname is null OR cnt1_fname is null) and schoolid <> '999999' and grade_level <> 13 and Enroll_Status in (0,-1) order by 1, 3 ;
 select  (select ABBREVIATION from SCHOOLS where students.SCHOOLID=SCHOOL_NUMBER) as School, 'Contact 2' as "Error Location", 'Parent name field blank' as Error, students.LASTFIRST, students.STUDENT_NUMBER, cnt2_rel, cnt2_fname, cnt2_lname from  s_sc_stu_contacts_x inner join students on s_sc_stu_contacts_x.studentsdcid=students.dcid where cnt2_rel is not null and (cnt2_lname is null OR cnt2_fname is null) and schoolid <> '999999' and grade_level <> 13 and Enroll_Status in (0,-1) order by 1, 3 ;
 select  (select ABBREVIATION from SCHOOLS where students.SCHOOLID=SCHOOL_NUMBER) as School, 'Contact 3' as "Error Location", 'Parent name field blank' as Error, students.LASTFIRST, students.STUDENT_NUMBER, cnt3_rel, cnt3_fname, cnt3_lname from  s_sc_stu_contacts_x inner join students on s_sc_stu_contacts_x.studentsdcid=students.dcid where cnt3_rel is not null and (cnt3_lname is null OR cnt3_fname is null) and schoolid <> '999999' and grade_level <> 13 and Enroll_Status in (0,-1) order by 1, 3 ;
 select  (select ABBREVIATION from SCHOOLS where students.SCHOOLID=SCHOOL_NUMBER) as School, 'Contact 4' as "Error Location", 'Parent name field blank' as Error, students.LASTFIRST, students.STUDENT_NUMBER, cnt4_rel, cnt4_fname, cnt4_lname from  s_sc_stu_contacts_x inner join students on s_sc_stu_contacts_x.studentsdcid=students.dcid where cnt4_rel is not null and (cnt4_lname is null OR cnt4_fname is null) and schoolid <> '999999' and grade_level <> 13 and Enroll_Status in (0,-1) order by 1, 3 ;
 select  (select ABBREVIATION from SCHOOLS where students.SCHOOLID=SCHOOL_NUMBER) as School, 'Contact 5' as "Error Location", 'Parent name field blank' as Error, students.LASTFIRST, students.STUDENT_NUMBER, cnt5_rel, cnt5_fname, cnt5_lname from  s_sc_stu_contacts_x inner join students on s_sc_stu_contacts_x.studentsdcid=students.dcid where cnt5_rel is not null and (cnt5_lname is null OR cnt5_fname is null) and schoolid <> '999999' and grade_level <> 13 and Enroll_Status in (0,-1) order by 1, 3 ;
 select  (select ABBREVIATION from SCHOOLS where students.SCHOOLID=SCHOOL_NUMBER) as School, 'Contact 6' as "Error Location", 'Parent name field blank' as Error, students.LASTFIRST, students.STUDENT_NUMBER, cnt6_rel, cnt6_fname, cnt6_lname from  s_sc_stu_contacts_x inner join students on s_sc_stu_contacts_x.studentsdcid=students.dcid where cnt6_rel is not null and (cnt6_lname is null OR cnt6_fname is null) and schoolid <> '999999' and grade_level <> 13 and Enroll_Status in (0,-1) order by 1, 3 ; 
 select  (select ABBREVIATION from SCHOOLS where students.SCHOOLID=SCHOOL_NUMBER) as School, 'Contact 7' as "Error Location", 'Parent name field blank' as Error, students.LASTFIRST, students.STUDENT_NUMBER, cnt7_rel, cnt7_fname, cnt7_lname from  s_sc_stu_contacts_x inner join students on s_sc_stu_contacts_x.studentsdcid=students.dcid where cnt7_rel is not null and (cnt7_lname is null OR cnt7_fname is null) and schoolid <> '999999' and grade_level <> 13 and Enroll_Status in (0,-1) order by 1, 3 ;
 select  (select ABBREVIATION from SCHOOLS where students.SCHOOLID=SCHOOL_NUMBER) as School, 'Contact 8' as "Error Location", 'Parent name field blank' as Error, students.LASTFIRST, students.STUDENT_NUMBER, cnt8_rel, cnt8_fname, cnt8_lname from  s_sc_stu_contacts_x inner join students on s_sc_stu_contacts_x.studentsdcid=students.dcid where cnt8_rel is not null and (cnt8_lname is null OR cnt8_fname is null) and schoolid <> '999999' and grade_level <> 13 and Enroll_Status in (0,-1) order by 1, 3 ;
 select  (select ABBREVIATION from SCHOOLS where students.SCHOOLID=SCHOOL_NUMBER) as School, 'Contact 9' as "Error Location", 'Parent name field blank' as Error, students.LASTFIRST, students.STUDENT_NUMBER, cnt9_rel, cnt9_fname, cnt9_lname from  s_sc_stu_contacts_x inner join students on s_sc_stu_contacts_x.studentsdcid=students.dcid where cnt9_rel is not null and (cnt9_lname is null OR cnt9_fname is null) and schoolid <> '999999' and grade_level <> 13 and Enroll_Status in (0,-1) order by 1, 3 ;
 select  (select ABBREVIATION from SCHOOLS where students.SCHOOLID=SCHOOL_NUMBER) as School, 'Contact 10' as "Error Location", 'Parent name field blank' as Error, students.LASTFIRST, students.STUDENT_NUMBER, cnt10_rel, cnt10_fname, cnt10_lname from  s_sc_stu_contacts_x inner join students on s_sc_stu_contacts_x.studentsdcid=students.dcid where cnt10_rel is not null and (cnt10_lname is null OR cnt10_fname is null) and schoolid <> '999999' and grade_level <> 13 and Enroll_Status in (0,-1) order by 1, 3 ;
 


--<<<<<<PHONE NUMBERS>>>>>>  
--Cell Phone
 select (select ABBREVIATION from SCHOOLS where students.SCHOOLID=SCHOOL_NUMBER) as "School", to_char(students.STUDENT_NUMBER), students.LASTFIRST, 'Contact 1 Cell' as "Error Location", s_sc_stu_contacts_x.cnt1_cphone, cnt1_lname || ', ' || cnt1_fname, LENGTH(s_sc_stu_contacts_x.cnt1_cphone) as "Length" from  students inner join s_sc_stu_contacts_x on students.dcid = s_sc_stu_contacts_x.studentsdcid where s_sc_stu_contacts_x.cnt1_cphone not like '___-___-____' and schoolid not in (999999, 43) and grade_level <> 13 and Enroll_Status = 0 order by 1, 3 ;
 select (select ABBREVIATION from SCHOOLS where students.SCHOOLID=SCHOOL_NUMBER) as "School", to_char(students.STUDENT_NUMBER), students.LASTFIRST, 'Contact 2 Cell' as "Error Location", s_sc_stu_contacts_x.cnt2_cphone, cnt2_lname || ', ' || cnt2_fname, LENGTH(s_sc_stu_contacts_x.cnt2_cphone) as "Length" from  students inner join s_sc_stu_contacts_x on students.dcid = s_sc_stu_contacts_x.studentsdcid where s_sc_stu_contacts_x.cnt2_cphone not like '___-___-____' and schoolid not in (999999, 43) and grade_level <> 13 and Enroll_Status in (0,-1) order by 1, 3 ;
 select (select ABBREVIATION from SCHOOLS where students.SCHOOLID=SCHOOL_NUMBER) as "School", to_char(students.STUDENT_NUMBER), students.LASTFIRST, 'Contact 3 Cell' as "Error Location", s_sc_stu_contacts_x.cnt3_cphone, cnt3_lname || ', ' || cnt3_fname, LENGTH(s_sc_stu_contacts_x.cnt3_cphone) as "Length" from  students inner join s_sc_stu_contacts_x on students.dcid = s_sc_stu_contacts_x.studentsdcid where s_sc_stu_contacts_x.cnt3_cphone not like '___-___-____' and schoolid not in (999999, 43) and grade_level <> 13 and Enroll_Status in (0,-1) order by 1, 3 ;
 select (select ABBREVIATION from SCHOOLS where students.SCHOOLID=SCHOOL_NUMBER) as "School", to_char(students.STUDENT_NUMBER), students.LASTFIRST, 'Contact 4 Cell' as "Error Location", s_sc_stu_contacts_x.cnt4_cphone, cnt4_lname || ', ' || cnt4_fname, LENGTH(s_sc_stu_contacts_x.cnt4_cphone) as "Length" from  students inner join s_sc_stu_contacts_x on students.dcid = s_sc_stu_contacts_x.studentsdcid where s_sc_stu_contacts_x.cnt4_cphone not like '___-___-____' and schoolid not in (999999, 43) and grade_level <> 13 and Enroll_Status in (0,-1) order by 1, 3 ;
 select (select ABBREVIATION from SCHOOLS where students.SCHOOLID=SCHOOL_NUMBER) as "School", to_char(students.STUDENT_NUMBER), students.LASTFIRST, 'Contact 5 Cell' as "Error Location", s_sc_stu_contacts_x.cnt5_cphone, cnt5_lname || ', ' || cnt5_fname, LENGTH(s_sc_stu_contacts_x.cnt5_cphone) as "Length" from  students inner join s_sc_stu_contacts_x on students.dcid = s_sc_stu_contacts_x.studentsdcid where s_sc_stu_contacts_x.cnt5_cphone not like '___-___-____' and schoolid not in (999999, 43) and grade_level <> 13 and Enroll_Status in (0,-1) order by 1, 3 ;
 select (select ABBREVIATION from SCHOOLS where students.SCHOOLID=SCHOOL_NUMBER) as "School", to_char(students.STUDENT_NUMBER), students.LASTFIRST, 'Contact 6 Cell' as "Error Location", s_sc_stu_contacts_x.cnt6_cphone, cnt6_lname || ', ' || cnt6_fname, LENGTH(s_sc_stu_contacts_x.cnt6_cphone) as "Length" from  students inner join s_sc_stu_contacts_x on students.dcid = s_sc_stu_contacts_x.studentsdcid where s_sc_stu_contacts_x.cnt6_cphone not like '___-___-____' and schoolid not in (999999, 43) and grade_level <> 13 and Enroll_Status in (0,-1) order by 1, 3 ;
 select (select ABBREVIATION from SCHOOLS where students.SCHOOLID=SCHOOL_NUMBER) as "School", to_char(students.STUDENT_NUMBER), students.LASTFIRST, 'Contact 7 Cell' as "Error Location", s_sc_stu_contacts_x.cnt7_cphone, cnt7_lname || ', ' || cnt7_fname, LENGTH(s_sc_stu_contacts_x.cnt7_cphone) as "Length" from  students inner join s_sc_stu_contacts_x on students.dcid = s_sc_stu_contacts_x.studentsdcid where s_sc_stu_contacts_x.cnt7_cphone not like '___-___-____' and schoolid not in (999999, 43) and grade_level <> 13 and Enroll_Status in (0,-1) order by 1, 3 ;
 select (select ABBREVIATION from SCHOOLS where students.SCHOOLID=SCHOOL_NUMBER) as "School", to_char(students.STUDENT_NUMBER), students.LASTFIRST, 'Contact 8 Cell' as "Error Location", s_sc_stu_contacts_x.cnt8_cphone, cnt8_lname || ', ' || cnt8_fname, LENGTH(s_sc_stu_contacts_x.cnt8_cphone) as "Length" from  students inner join s_sc_stu_contacts_x on students.dcid = s_sc_stu_contacts_x.studentsdcid where s_sc_stu_contacts_x.cnt8_cphone not like '___-___-____' and schoolid not in (999999, 43) and grade_level <> 13 and Enroll_Status in (0,-1) order by 1, 3 ;
 select (select ABBREVIATION from SCHOOLS where students.SCHOOLID=SCHOOL_NUMBER) as "School", to_char(students.STUDENT_NUMBER), students.LASTFIRST, 'Contact 9 Cell' as "Error Location", s_sc_stu_contacts_x.cnt9_cphone, cnt9_lname || ', ' || cnt9_fname, LENGTH(s_sc_stu_contacts_x.cnt9_cphone) as "Length" from  students inner join s_sc_stu_contacts_x on students.dcid = s_sc_stu_contacts_x.studentsdcid where s_sc_stu_contacts_x.cnt9_cphone not like '___-___-____' and schoolid not in (999999, 43) and grade_level <> 13 and Enroll_Status in (0,-1) order by 1, 3 ;
 select (select ABBREVIATION from SCHOOLS where students.SCHOOLID=SCHOOL_NUMBER) as "School", to_char(students.STUDENT_NUMBER), students.LASTFIRST, 'Contact 10 Cell' as "Error Location", s_sc_stu_contacts_x.cnt10_cphone, cnt10_lname || ', ' || cnt10_fname, LENGTH(s_sc_stu_contacts_x.cnt10_cphone) as "Length" from  students inner join s_sc_stu_contacts_x on students.dcid = s_sc_stu_contacts_x.studentsdcid where s_sc_stu_contacts_x.cnt10_cphone not like '___-___-____' and schoolid not in (999999, 43) and grade_level <> 13 and Enroll_Status in (0,-1) order by 1, 3 ;
 
-- Work Phone
 select (select ABBREVIATION from SCHOOLS where students.SCHOOLID=SCHOOL_NUMBER) as "School", to_char(to_char(students.STUDENT_NUMBER)), students.LASTFIRST, 'Contact 1 Work' as "Error Location", to_char(s_sc_stu_contacts_x.cnt1_wphone), cnt1_lname || ', ' || cnt1_fname, LENGTH(s_sc_stu_contacts_x.cnt1_wphone) as "Length" from  students inner join s_sc_stu_contacts_x on students.dcid = s_sc_stu_contacts_x.studentsdcid WHERE  (s_sc_stu_contacts_x.cnt1_wphone not like '___-___-____' AND s_sc_stu_contacts_x.cnt1_wphone not like '___-___-____ (%)' ) and schoolid not in (999999, 43) and grade_level <> 13 and Enroll_Status = 0 order by 1, 3 ;
 select (select ABBREVIATION from SCHOOLS where students.SCHOOLID=SCHOOL_NUMBER) as "School", to_char(to_char(students.STUDENT_NUMBER)), students.LASTFIRST, 'Contact 2 Work' as "Error Location", to_char(s_sc_stu_contacts_x.cnt2_wphone), cnt2_lname || ', ' || cnt2_fname, LENGTH(s_sc_stu_contacts_x.cnt2_wphone) as "Length" from  students inner join s_sc_stu_contacts_x on students.dcid = s_sc_stu_contacts_x.studentsdcid WHERE (s_sc_stu_contacts_x.cnt2_wphone not like '___-___-____' AND s_sc_stu_contacts_x.cnt2_wphone not like '___-___-____ (%)' ) and schoolid not in (999999, 43) and grade_level <> 13 and Enroll_Status in (0,-1) order by 1, 3 ;
 select (select ABBREVIATION from SCHOOLS where students.SCHOOLID=SCHOOL_NUMBER) as "School", to_char(students.STUDENT_NUMBER), students.LASTFIRST, 'Contact 3 Work' as "Error Location", to_char(s_sc_stu_contacts_x.cnt3_wphone), cnt3_lname || ', ' || cnt3_fname, LENGTH(s_sc_stu_contacts_x.cnt3_wphone) as "Length" from  students inner join s_sc_stu_contacts_x on students.dcid = s_sc_stu_contacts_x.studentsdcid WHERE (s_sc_stu_contacts_x.cnt3_wphone not like '___-___-____' AND s_sc_stu_contacts_x.cnt3_wphone not like '___-___-____ (%)' ) and schoolid not in (999999, 43) and grade_level <> 13 and Enroll_Status in (0,-1) order by 1, 3 ;
 select (select ABBREVIATION from SCHOOLS where students.SCHOOLID=SCHOOL_NUMBER) as "School", to_char(students.STUDENT_NUMBER), students.LASTFIRST, 'Contact 4 Work' as "Error Location", to_char(s_sc_stu_contacts_x.cnt4_wphone), cnt4_lname || ', ' || cnt4_fname, LENGTH(s_sc_stu_contacts_x.cnt4_wphone) as "Length" from  students inner join s_sc_stu_contacts_x on students.dcid = s_sc_stu_contacts_x.studentsdcid WHERE (s_sc_stu_contacts_x.cnt4_wphone not like '___-___-____' AND s_sc_stu_contacts_x.cnt4_wphone not like '___-___-____ (%)' ) and schoolid not in (999999, 43) and grade_level <> 13 and Enroll_Status in (0,-1) order by 1, 3 ;
 select (select ABBREVIATION from SCHOOLS where students.SCHOOLID=SCHOOL_NUMBER) as "School", to_char(students.STUDENT_NUMBER), students.LASTFIRST, 'Contact 5 Work' as "Error Location", to_char(s_sc_stu_contacts_x.cnt5_wphone), cnt5_lname || ', ' || cnt5_fname, LENGTH(s_sc_stu_contacts_x.cnt5_wphone) as "Length" from  students inner join s_sc_stu_contacts_x on students.dcid = s_sc_stu_contacts_x.studentsdcid WHERE (s_sc_stu_contacts_x.cnt5_wphone not like '___-___-____' AND s_sc_stu_contacts_x.cnt5_wphone not like '___-___-____ (%)' ) and schoolid not in (999999, 43) and grade_level <> 13 and Enroll_Status in (0,-1) order by 1, 3 ;
 select (select ABBREVIATION from SCHOOLS where students.SCHOOLID=SCHOOL_NUMBER) as "School", to_char(students.STUDENT_NUMBER), students.LASTFIRST, 'Contact 6 Work' as "Error Location", to_char(s_sc_stu_contacts_x.cnt6_wphone), cnt6_lname || ', ' || cnt6_fname, LENGTH(s_sc_stu_contacts_x.cnt6_wphone) as "Length" from  students inner join s_sc_stu_contacts_x on students.dcid = s_sc_stu_contacts_x.studentsdcid WHERE (s_sc_stu_contacts_x.cnt6_wphone not like '___-___-____' AND s_sc_stu_contacts_x.cnt6_wphone not like '___-___-____ (%)' ) and schoolid not in (999999, 43) and grade_level <> 13 and Enroll_Status in (0,-1) order by 1, 3 ;
 select (select ABBREVIATION from SCHOOLS where students.SCHOOLID=SCHOOL_NUMBER) as "School", to_char(students.STUDENT_NUMBER), students.LASTFIRST, 'Contact 7 Work' as "Error Location", to_char(s_sc_stu_contacts_x.cnt7_wphone), cnt7_lname || ', ' || cnt7_fname, LENGTH(s_sc_stu_contacts_x.cnt7_wphone) as "Length" from  students inner join s_sc_stu_contacts_x on students.dcid = s_sc_stu_contacts_x.studentsdcid WHERE (s_sc_stu_contacts_x.cnt7_wphone not like '___-___-____' AND s_sc_stu_contacts_x.cnt7_wphone not like '___-___-____ (%)' ) and schoolid not in (999999, 43) and grade_level <> 13 and Enroll_Status in (0,-1) order by 1, 3 ;
 select (select ABBREVIATION from SCHOOLS where students.SCHOOLID=SCHOOL_NUMBER) as "School", to_char(students.STUDENT_NUMBER), students.LASTFIRST, 'Contact 8 Work' as "Error Location", to_char(s_sc_stu_contacts_x.cnt8_wphone), cnt8_lname || ', ' || cnt8_fname, LENGTH(s_sc_stu_contacts_x.cnt8_wphone) as "Length" from  students inner join s_sc_stu_contacts_x on students.dcid = s_sc_stu_contacts_x.studentsdcid WHERE (s_sc_stu_contacts_x.cnt8_wphone not like '___-___-____' AND s_sc_stu_contacts_x.cnt8_wphone not like '___-___-____ (%)' ) and schoolid not in (999999, 43) and grade_level <> 13 and Enroll_Status in (0,-1) order by 1, 3 ;
 select (select ABBREVIATION from SCHOOLS where students.SCHOOLID=SCHOOL_NUMBER) as "School", to_char(students.STUDENT_NUMBER), students.LASTFIRST, 'Contact 9 Work' as "Error Location", to_char(s_sc_stu_contacts_x.cnt9_wphone), cnt9_lname || ', ' || cnt9_fname, LENGTH(s_sc_stu_contacts_x.cnt9_wphone) as "Length" from  students inner join s_sc_stu_contacts_x on students.dcid = s_sc_stu_contacts_x.studentsdcid WHERE (s_sc_stu_contacts_x.cnt9_wphone not like '___-___-____' AND s_sc_stu_contacts_x.cnt9_wphone not like '___-___-____ (%)' ) and schoolid not in (999999, 43) and grade_level <> 13 and Enroll_Status in (0,-1) order by 1, 3 ;
 select (select ABBREVIATION from SCHOOLS where students.SCHOOLID=SCHOOL_NUMBER) as "School", to_char(students.STUDENT_NUMBER), students.LASTFIRST, 'Contact 10 Work' as "Error Location", to_char(s_sc_stu_contacts_x.cnt10_wphone), cnt10_lname || ', ' || cnt10_fname, LENGTH(s_sc_stu_contacts_x.cnt10_wphone) as "Length" from  students inner join s_sc_stu_contacts_x on students.dcid = s_sc_stu_contacts_x.studentsdcid WHERE (s_sc_stu_contacts_x.cnt10_wphone not like '___-___-____' AND s_sc_stu_contacts_x.cnt10_wphone not like '___-___-____ (%)' ) and schoolid not in (999999, 43) and grade_level <> 13 and Enroll_Status in (0,-1) order by 1, 3 ;
 
 
--home phone
 select (select ABBREVIATION from SCHOOLS where students.SCHOOLID=SCHOOL_NUMBER) as "School", to_char(students.STUDENT_NUMBER), students.LASTFIRST, 'Contact 1 Home' as "Error Location", s_sc_stu_contacts_x.cnt1_hphone, cnt1_lname || ', ' || cnt1_fname, LENGTH(s_sc_stu_contacts_x.cnt1_hphone) as "Length" from  students inner join s_sc_stu_contacts_x on students.dcid = s_sc_stu_contacts_x.studentsdcid where s_sc_stu_contacts_x.cnt1_hphone not like '___-___-____' and schoolid not in (999999, 43) and grade_level <> 13 and Enroll_Status = 0 order by 1, 3 ;
 select (select ABBREVIATION from SCHOOLS where students.SCHOOLID=SCHOOL_NUMBER) as "School", to_char(students.STUDENT_NUMBER), students.LASTFIRST, 'Contact 2 Home' as "Error Location", s_sc_stu_contacts_x.cnt2_hphone, cnt2_lname || ', ' || cnt2_fname, LENGTH(s_sc_stu_contacts_x.cnt2_hphone) as "Length" from  students inner join s_sc_stu_contacts_x on students.dcid = s_sc_stu_contacts_x.studentsdcid where s_sc_stu_contacts_x.cnt2_hphone not like '___-___-____' and schoolid not in (999999, 43) and grade_level <> 13 and Enroll_Status in (0,-1) order by 1, 3 ;
 select (select ABBREVIATION from SCHOOLS where students.SCHOOLID=SCHOOL_NUMBER) as "School", to_char(students.STUDENT_NUMBER), students.LASTFIRST, 'Contact 3 Home' as "Error Location", s_sc_stu_contacts_x.cnt3_hphone, cnt3_lname || ', ' || cnt3_fname, LENGTH(s_sc_stu_contacts_x.cnt3_hphone) as "Length" from  students inner join s_sc_stu_contacts_x on students.dcid = s_sc_stu_contacts_x.studentsdcid where s_sc_stu_contacts_x.cnt3_hphone not like '___-___-____' and schoolid not in (999999, 43) and grade_level <> 13 and Enroll_Status in (0,-1) order by 1, 3 ;
 select (select ABBREVIATION from SCHOOLS where students.SCHOOLID=SCHOOL_NUMBER) as "School", to_char(students.STUDENT_NUMBER), students.LASTFIRST, 'Contact 4 Home' as "Error Location", s_sc_stu_contacts_x.cnt4_hphone, cnt4_lname || ', ' || cnt4_fname, LENGTH(s_sc_stu_contacts_x.cnt4_hphone) as "Length" from  students inner join s_sc_stu_contacts_x on students.dcid = s_sc_stu_contacts_x.studentsdcid where s_sc_stu_contacts_x.cnt4_hphone not like '___-___-____' and schoolid not in (999999, 43) and grade_level <> 13 and Enroll_Status in (0,-1) order by 1, 3 ;
 select (select ABBREVIATION from SCHOOLS where students.SCHOOLID=SCHOOL_NUMBER) as "School", to_char(students.STUDENT_NUMBER), students.LASTFIRST, 'Contact 5 Home' as "Error Location", s_sc_stu_contacts_x.cnt5_hphone, cnt5_lname || ', ' || cnt5_fname, LENGTH(s_sc_stu_contacts_x.cnt5_hphone) as "Length" from  students inner join s_sc_stu_contacts_x on students.dcid = s_sc_stu_contacts_x.studentsdcid where s_sc_stu_contacts_x.cnt5_hphone not like '___-___-____' and schoolid not in (999999, 43) and grade_level <> 13 and Enroll_Status in (0,-1) order by 1, 3 ;
 select (select ABBREVIATION from SCHOOLS where students.SCHOOLID=SCHOOL_NUMBER) as "School", to_char(students.STUDENT_NUMBER), students.LASTFIRST, 'Contact 6 Home' as "Error Location", s_sc_stu_contacts_x.cnt6_hphone, cnt6_lname || ', ' || cnt6_fname, LENGTH(s_sc_stu_contacts_x.cnt6_hphone) as "Length" from  students inner join s_sc_stu_contacts_x on students.dcid = s_sc_stu_contacts_x.studentsdcid where s_sc_stu_contacts_x.cnt6_hphone not like '___-___-____' and schoolid not in (999999, 43) and grade_level <> 13 and Enroll_Status in (0,-1) order by 1, 3 ;
 select (select ABBREVIATION from SCHOOLS where students.SCHOOLID=SCHOOL_NUMBER) as "School", to_char(students.STUDENT_NUMBER), students.LASTFIRST, 'Contact 7 Home' as "Error Location", s_sc_stu_contacts_x.cnt7_hphone, cnt7_lname || ', ' || cnt7_fname, LENGTH(s_sc_stu_contacts_x.cnt7_hphone) as "Length" from  students inner join s_sc_stu_contacts_x on students.dcid = s_sc_stu_contacts_x.studentsdcid where s_sc_stu_contacts_x.cnt7_hphone not like '___-___-____' and schoolid not in (999999, 43) and grade_level <> 13 and Enroll_Status in (0,-1) order by 1, 3 ;
 select (select ABBREVIATION from SCHOOLS where students.SCHOOLID=SCHOOL_NUMBER) as "School", to_char(students.STUDENT_NUMBER), students.LASTFIRST, 'Contact 8 Home' as "Error Location", s_sc_stu_contacts_x.cnt8_hphone, cnt8_lname || ', ' || cnt8_fname, LENGTH(s_sc_stu_contacts_x.cnt8_hphone) as "Length" from  students inner join s_sc_stu_contacts_x on students.dcid = s_sc_stu_contacts_x.studentsdcid where s_sc_stu_contacts_x.cnt8_hphone not like '___-___-____' and schoolid not in (999999, 43) and grade_level <> 13 and Enroll_Status in (0,-1) order by 1, 3 ;
 select (select ABBREVIATION from SCHOOLS where students.SCHOOLID=SCHOOL_NUMBER) as "School", to_char(students.STUDENT_NUMBER), students.LASTFIRST, 'Contact 9 Home' as "Error Location", s_sc_stu_contacts_x.cnt9_hphone, cnt9_lname || ', ' || cnt9_fname, LENGTH(s_sc_stu_contacts_x.cnt9_hphone) as "Length" from  students inner join s_sc_stu_contacts_x on students.dcid = s_sc_stu_contacts_x.studentsdcid where s_sc_stu_contacts_x.cnt9_hphone not like '___-___-____' and schoolid not in (999999, 43) and grade_level <> 13 and Enroll_Status in (0,-1) order by 1, 3 ;
 select (select ABBREVIATION from SCHOOLS where students.SCHOOLID=SCHOOL_NUMBER) as "School", to_char(students.STUDENT_NUMBER), students.LASTFIRST, 'Contact 10 Home' as "Error Location", s_sc_stu_contacts_x.cnt10_hphone, cnt10_lname || ', ' || cnt10_fname, LENGTH(s_sc_stu_contacts_x.cnt10_hphone) as "Length" from  students inner join s_sc_stu_contacts_x on students.dcid = s_sc_stu_contacts_x.studentsdcid where s_sc_stu_contacts_x.cnt10_hphone not like '___-___-____' and schoolid not in (999999, 43) and grade_level <> 13 and Enroll_Status in (0,-1) order by 1, 3 ;
 
--<<<<<<EMAILS>>>>>>  
--Emails w/out @
 select (select ABBREVIATION from SCHOOLS where students.SCHOOLID=SCHOOL_NUMBER) as "School", to_char(students.STUDENT_NUMBER), students.LASTFIRST, 'Contact 1 Email' as "Error Location", s_sc_stu_contacts_x.cnt1_email, cnt1_lname || ', ' || cnt1_fname from  students inner join s_sc_stu_contacts_x on students.dcid = s_sc_stu_contacts_x.studentsdcid where cnt1_email not like '%@%' and schoolid not in (999999, 43) and grade_level <> 13 and Enroll_Status = 0 order by 1, 3 ;
 select (select ABBREVIATION from SCHOOLS where students.SCHOOLID=SCHOOL_NUMBER) as "School", to_char(students.STUDENT_NUMBER), students.LASTFIRST, 'Contact 2 Email' as "Error Location", s_sc_stu_contacts_x.cnt2_email, cnt2_lname || ', ' || cnt2_fname from  students inner join s_sc_stu_contacts_x on students.dcid = s_sc_stu_contacts_x.studentsdcid where cnt2_email not like '%@%' and schoolid not in (999999, 43) and grade_level <> 13 and Enroll_Status = 0 order by 1, 3 ;
 select (select ABBREVIATION from SCHOOLS where students.SCHOOLID=SCHOOL_NUMBER) as "School", to_char(students.STUDENT_NUMBER), students.LASTFIRST, 'Contact 3 Email' as "Error Location", s_sc_stu_contacts_x.cnt3_email, cnt3_lname || ', ' || cnt3_fname from  students inner join s_sc_stu_contacts_x on students.dcid = s_sc_stu_contacts_x.studentsdcid where cnt3_email not like '%@%' and schoolid not in (999999, 43) and grade_level <> 13 and Enroll_Status = 0 order by 1, 3 ;
 select (select ABBREVIATION from SCHOOLS where students.SCHOOLID=SCHOOL_NUMBER) as "School", to_char(students.STUDENT_NUMBER), students.LASTFIRST, 'Contact 4 Email' as "Error Location", s_sc_stu_contacts_x.cnt4_email, cnt4_lname || ', ' || cnt4_fname from  students inner join s_sc_stu_contacts_x on students.dcid = s_sc_stu_contacts_x.studentsdcid where cnt4_email not like '%@%' and schoolid not in (999999, 43) and grade_level <> 13 and Enroll_Status = 0 order by 1, 3 ;
 select (select ABBREVIATION from SCHOOLS where students.SCHOOLID=SCHOOL_NUMBER) as "School", to_char(students.STUDENT_NUMBER), students.LASTFIRST, 'Contact 5 Email' as "Error Location", s_sc_stu_contacts_x.cnt5_email, cnt5_lname || ', ' || cnt5_fname from  students inner join s_sc_stu_contacts_x on students.dcid = s_sc_stu_contacts_x.studentsdcid where cnt5_email not like '%@%' and schoolid not in (999999, 43) and grade_level <> 13 and Enroll_Status = 0 order by 1, 3 ;
 select (select ABBREVIATION from SCHOOLS where students.SCHOOLID=SCHOOL_NUMBER) as "School", to_char(students.STUDENT_NUMBER), students.LASTFIRST, 'Contact 6 Email' as "Error Location", s_sc_stu_contacts_x.cnt6_email, cnt6_lname || ', ' || cnt6_fname from  students inner join s_sc_stu_contacts_x on students.dcid = s_sc_stu_contacts_x.studentsdcid where cnt6_email not like '%@%' and schoolid not in (999999, 43) and grade_level <> 13 and Enroll_Status = 0 order by 1, 3 ;
 select (select ABBREVIATION from SCHOOLS where students.SCHOOLID=SCHOOL_NUMBER) as "School", to_char(students.STUDENT_NUMBER), students.LASTFIRST, 'Contact 7 Email' as "Error Location", s_sc_stu_contacts_x.cnt7_email, cnt7_lname || ', ' || cnt7_fname from  students inner join s_sc_stu_contacts_x on students.dcid = s_sc_stu_contacts_x.studentsdcid where cnt7_email not like '%@%' and schoolid not in (999999, 43) and grade_level <> 13 and Enroll_Status = 0 order by 1, 3 ;
 select (select ABBREVIATION from SCHOOLS where students.SCHOOLID=SCHOOL_NUMBER) as "School", to_char(students.STUDENT_NUMBER), students.LASTFIRST, 'Contact 8 Email' as "Error Location", s_sc_stu_contacts_x.cnt8_email, cnt8_lname || ', ' || cnt8_fname from  students inner join s_sc_stu_contacts_x on students.dcid = s_sc_stu_contacts_x.studentsdcid where cnt8_email not like '%@%' and schoolid not in (999999, 43) and grade_level <> 13 and Enroll_Status = 0 order by 1, 3 ;
 select (select ABBREVIATION from SCHOOLS where students.SCHOOLID=SCHOOL_NUMBER) as "School", to_char(students.STUDENT_NUMBER), students.LASTFIRST, 'Contact 9 Email' as "Error Location", s_sc_stu_contacts_x.cnt9_email, cnt9_lname || ', ' || cnt9_fname from  students inner join s_sc_stu_contacts_x on students.dcid = s_sc_stu_contacts_x.studentsdcid where cnt9_email not like '%@%' and schoolid not in (999999, 43) and grade_level <> 13 and Enroll_Status = 0 order by 1, 3 ;
 select (select ABBREVIATION from SCHOOLS where students.SCHOOLID=SCHOOL_NUMBER) as "School", to_char(students.STUDENT_NUMBER), students.LASTFIRST, 'Contact 10 Email' as "Error Location", s_sc_stu_contacts_x.cnt10_email, cnt10_lname || ', ' || cnt10_fname from  students inner join s_sc_stu_contacts_x on students.dcid = s_sc_stu_contacts_x.studentsdcid where cnt10_email not like '%@%' and schoolid not in (999999, 43) and grade_level <> 13 and Enroll_Status = 0 order by 1, 3 ;

 --Comma only in parent name (wip) 
 select  students.SCHOOLID, students.LASTFIRST, students.ENROLL_STATUS, to_char(students.STUDENT_NUMBER), cnt1_rel, cnt1_fname, cnt1_lname from  s_sc_stu_contacts_x inner join students on s_sc_stu_contacts_x.studentsdcid=students.dcid where cnt1_fname || cnt1_lname = ' , ' and schoolid not in ('999999','43') and Enroll_Status in (0,-1) ;
 
 --Comma only in parent name (wip) 
 select  students.SCHOOLID, students.LASTFIRST, students.ENROLL_STATUS, to_char(students.STUDENT_NUMBER), cnt1_rel, cnt1_fname, cnt1_lname from  s_sc_stu_contacts_x inner join students on s_sc_stu_contacts_x.studentsdcid=students.dcid where cnt1_fname || cnt1_lname LIKE ',' and schoolid not in ('999999','43') and Enroll_Status in (0,-1);
TRIM (BOTH' ' FROM s_sc_stu_contacts_x.cnt1_cphone);

--<<<Deleting Work Numbers that are parenthesis only>>>
select s_sc_stu_contacts_x.cnt1_wphone, LENGTH(s_sc_stu_contacts_x.cnt1_wphone) as "Length" from  students inner join s_sc_stu_contacts_x on students.dcid = s_sc_stu_contacts_x.studentsdcid WHERE  (s_sc_stu_contacts_x.cnt1_wphone not like '___-___-____' AND s_sc_stu_contacts_x.cnt1_wphone not like '___-___-____ (%)' ) and schoolid not in (999999, 43) and grade_level <> 13 and Enroll_Status in (0,-1) AND LENGTH(s_sc_stu_contacts_x.cnt1_wphone) = 2;
UPDATE s_sc_stu_contacts_x
SET s_sc_stu_contacts_x.cnt1_wphone = null
WHERE studentsdcid in (SELECT students.dcid from  students inner join s_sc_stu_contacts_x on students.dcid = s_sc_stu_contacts_x.studentsdcid WHERE  (s_sc_stu_contacts_x.cnt1_wphone not like '___-___-____' AND s_sc_stu_contacts_x.cnt1_wphone not like '___-___-____ (%)' ) and schoolid not in (999999, 43) and grade_level <> 13 and Enroll_Status in (0,-1) AND LENGTH(s_sc_stu_contacts_x.cnt1_wphone) = 2);

select s_sc_stu_contacts_x.cnt2_wphone, LENGTH(s_sc_stu_contacts_x.cnt2_wphone) as "Length" from  students inner join s_sc_stu_contacts_x on students.dcid = s_sc_stu_contacts_x.studentsdcid WHERE (s_sc_stu_contacts_x.cnt2_wphone not like '___-___-____' AND s_sc_stu_contacts_x.cnt2_wphone not like '___-___-____ (%)' ) and schoolid not in (999999, 43) and grade_level <> 13 and Enroll_Status in (0,-1) AND LENGTH(s_sc_stu_contacts_x.cnt2_wphone) = 2;
UPDATE s_sc_stu_contacts_x
SET s_sc_stu_contacts_x.cnt2_wphone = null
WHERE studentsdcid in (SELECT students.dcid from  students inner join s_sc_stu_contacts_x on students.dcid = s_sc_stu_contacts_x.studentsdcid WHERE  (s_sc_stu_contacts_x.cnt2_wphone not like '___-___-____' AND s_sc_stu_contacts_x.cnt2_wphone not like '___-___-____ (%)' ) and schoolid not in (999999, 43) and grade_level <> 13 and Enroll_Status in (0,-1) AND LENGTH(s_sc_stu_contacts_x.cnt2_wphone) = 2);

select s_sc_stu_contacts_x.cnt3_wphone, LENGTH(s_sc_stu_contacts_x.cnt3_wphone) as "Length" from  students inner join s_sc_stu_contacts_x on students.dcid = s_sc_stu_contacts_x.studentsdcid WHERE (s_sc_stu_contacts_x.cnt3_wphone not like '___-___-____' AND s_sc_stu_contacts_x.cnt3_wphone not like '___-___-____ (%)' ) and schoolid not in (999999, 43) and grade_level <> 13 and Enroll_Status in (0,-1) AND LENGTH(s_sc_stu_contacts_x.cnt3_wphone) = 2;
UPDATE s_sc_stu_contacts_x
SET s_sc_stu_contacts_x.cnt3_wphone = null
WHERE studentsdcid in (SELECT students.dcid from  students inner join s_sc_stu_contacts_x on students.dcid = s_sc_stu_contacts_x.studentsdcid WHERE  (s_sc_stu_contacts_x.cnt3_wphone not like '___-___-____' AND s_sc_stu_contacts_x.cnt3_wphone not like '___-___-____ (%)' ) and schoolid not in (999999, 43) and grade_level <> 13 and Enroll_Status in (0,-1) AND LENGTH(s_sc_stu_contacts_x.cnt3_wphone) = 2);

select s_sc_stu_contacts_x.cnt4_wphone, LENGTH(s_sc_stu_contacts_x.cnt4_wphone) as "Length" from  students inner join s_sc_stu_contacts_x on students.dcid = s_sc_stu_contacts_x.studentsdcid WHERE (s_sc_stu_contacts_x.cnt4_wphone not like '___-___-____' AND s_sc_stu_contacts_x.cnt4_wphone not like '___-___-____ (%)' ) and schoolid not in (999999, 43) and grade_level <> 13 and Enroll_Status in (0,-1) AND LENGTH(s_sc_stu_contacts_x.cnt4_wphone) = 2;
UPDATE s_sc_stu_contacts_x
SET s_sc_stu_contacts_x.cnt4_wphone = null
WHERE studentsdcid in (SELECT students.dcid from  students inner join s_sc_stu_contacts_x on students.dcid = s_sc_stu_contacts_x.studentsdcid WHERE  (s_sc_stu_contacts_x.cnt4_wphone not like '___-___-____' AND s_sc_stu_contacts_x.cnt4_wphone not like '___-___-____ (%)' ) and schoolid not in (999999, 43) and grade_level <> 13 and Enroll_Status in (0,-1) AND LENGTH(s_sc_stu_contacts_x.cnt4_wphone) = 2);

select s_sc_stu_contacts_x.cnt5_wphone, LENGTH(s_sc_stu_contacts_x.cnt5_wphone) as "Length" from  students inner join s_sc_stu_contacts_x on students.dcid = s_sc_stu_contacts_x.studentsdcid WHERE (s_sc_stu_contacts_x.cnt5_wphone not like '___-___-____' AND s_sc_stu_contacts_x.cnt5_wphone not like '___-___-____ (%)' ) and schoolid not in (999999, 43) and grade_level <> 13 and Enroll_Status in (0,-1) AND LENGTH(s_sc_stu_contacts_x.cnt5_wphone) = 2;
UPDATE s_sc_stu_contacts_x
SET s_sc_stu_contacts_x.cnt5_wphone = null
WHERE studentsdcid in (SELECT students.dcid from  students inner join s_sc_stu_contacts_x on students.dcid = s_sc_stu_contacts_x.studentsdcid WHERE  (s_sc_stu_contacts_x.cnt5_wphone not like '___-___-____' AND s_sc_stu_contacts_x.cnt5_wphone not like '___-___-____ (%)' ) and schoolid not in (999999, 43) and grade_level <> 13 and Enroll_Status in (0,-1) AND LENGTH(s_sc_stu_contacts_x.cnt5_wphone) = 2);

select s_sc_stu_contacts_x.cnt6_wphone, LENGTH(s_sc_stu_contacts_x.cnt6_wphone) as "Length" from  students inner join s_sc_stu_contacts_x on students.dcid = s_sc_stu_contacts_x.studentsdcid WHERE (s_sc_stu_contacts_x.cnt6_wphone not like '___-___-____' AND s_sc_stu_contacts_x.cnt6_wphone not like '___-___-____ (%)' ) and schoolid not in (999999, 43) and grade_level <> 13 and Enroll_Status in (0,-1) AND LENGTH(s_sc_stu_contacts_x.cnt6_wphone) = 2;
UPDATE s_sc_stu_contacts_x
SET s_sc_stu_contacts_x.cnt6_wphone = null
WHERE studentsdcid in (SELECT students.dcid from  students inner join s_sc_stu_contacts_x on students.dcid = s_sc_stu_contacts_x.studentsdcid WHERE  (s_sc_stu_contacts_x.cnt6_wphone not like '___-___-____' AND s_sc_stu_contacts_x.cnt6_wphone not like '___-___-____ (%)' ) and schoolid not in (999999, 43) and grade_level <> 13 and Enroll_Status in (0,-1) AND LENGTH(s_sc_stu_contacts_x.cnt6_wphone) = 2);

select s_sc_stu_contacts_x.cnt7_wphone, LENGTH(s_sc_stu_contacts_x.cnt7_wphone) as "Length" from  students inner join s_sc_stu_contacts_x on students.dcid = s_sc_stu_contacts_x.studentsdcid WHERE (s_sc_stu_contacts_x.cnt7_wphone not like '___-___-____' AND s_sc_stu_contacts_x.cnt7_wphone not like '___-___-____ (%)' ) and schoolid not in (999999, 43) and grade_level <> 13 and Enroll_Status in (0,-1) AND LENGTH(s_sc_stu_contacts_x.cnt7_wphone) = 2;
UPDATE s_sc_stu_contacts_x
SET s_sc_stu_contacts_x.cnt7_wphone = null
WHERE studentsdcid in (SELECT students.dcid from  students inner join s_sc_stu_contacts_x on students.dcid = s_sc_stu_contacts_x.studentsdcid WHERE  (s_sc_stu_contacts_x.cnt7_wphone not like '___-___-____' AND s_sc_stu_contacts_x.cnt7_wphone not like '___-___-____ (%)' ) and schoolid not in (999999, 43) and grade_level <> 13 and Enroll_Status in (0,-1) AND LENGTH(s_sc_stu_contacts_x.cnt7_wphone) = 2);

select s_sc_stu_contacts_x.cnt8_wphone, LENGTH(s_sc_stu_contacts_x.cnt8_wphone) as "Length" from  students inner join s_sc_stu_contacts_x on students.dcid = s_sc_stu_contacts_x.studentsdcid WHERE (s_sc_stu_contacts_x.cnt8_wphone not like '___-___-____' AND s_sc_stu_contacts_x.cnt8_wphone not like '___-___-____ (%)' ) and schoolid not in (999999, 43) and grade_level <> 13 and Enroll_Status in (0,-1) AND LENGTH(s_sc_stu_contacts_x.cnt8_wphone) = 2;
UPDATE s_sc_stu_contacts_x
SET s_sc_stu_contacts_x.cnt8_wphone = null
WHERE studentsdcid in (SELECT students.dcid from  students inner join s_sc_stu_contacts_x on students.dcid = s_sc_stu_contacts_x.studentsdcid WHERE  (s_sc_stu_contacts_x.cnt8_wphone not like '___-___-____' AND s_sc_stu_contacts_x.cnt8_wphone not like '___-___-____ (%)' ) and schoolid not in (999999, 43) and grade_level <> 13 and Enroll_Status in (0,-1) AND LENGTH(s_sc_stu_contacts_x.cnt8_wphone) = 2);

select s_sc_stu_contacts_x.cnt9_wphone, LENGTH(s_sc_stu_contacts_x.cnt9_wphone) as "Length" from  students inner join s_sc_stu_contacts_x on students.dcid = s_sc_stu_contacts_x.studentsdcid WHERE (s_sc_stu_contacts_x.cnt9_wphone not like '___-___-____' AND s_sc_stu_contacts_x.cnt9_wphone not like '___-___-____ (%)' ) and schoolid not in (999999, 43) and grade_level <> 13 and Enroll_Status in (0,-1) AND LENGTH(s_sc_stu_contacts_x.cnt9_wphone) = 2;
UPDATE s_sc_stu_contacts_x
SET s_sc_stu_contacts_x.cnt9_wphone = null
WHERE studentsdcid in (SELECT students.dcid from  students inner join s_sc_stu_contacts_x on students.dcid = s_sc_stu_contacts_x.studentsdcid WHERE  (s_sc_stu_contacts_x.cnt9_wphone not like '___-___-____' AND s_sc_stu_contacts_x.cnt9_wphone not like '___-___-____ (%)' ) and schoolid not in (999999, 43) and grade_level <> 13 and Enroll_Status in (0,-1) AND LENGTH(s_sc_stu_contacts_x.cnt9_wphone) = 2);

select s_sc_stu_contacts_x.cnt10_wphone, LENGTH(s_sc_stu_contacts_x.cnt10_wphone) as "Length" from  students inner join s_sc_stu_contacts_x on students.dcid = s_sc_stu_contacts_x.studentsdcid WHERE (s_sc_stu_contacts_x.cnt10_wphone not like '___-___-____' AND s_sc_stu_contacts_x.cnt10_wphone not like '___-___-____ (%)' ) and schoolid not in (999999, 43) and grade_level <> 13 and Enroll_Status in (0,-1) AND LENGTH(s_sc_stu_contacts_x.cnt10_wphone) = 2;
UPDATE s_sc_stu_contacts_x
SET s_sc_stu_contacts_x.cnt10_wphone = null
WHERE studentsdcid in (SELECT students.dcid from  students inner join s_sc_stu_contacts_x on students.dcid = s_sc_stu_contacts_x.studentsdcid WHERE  (s_sc_stu_contacts_x.cnt10_wphone not like '___-___-____' AND s_sc_stu_contacts_x.cnt10_wphone not like '___-___-____ (%)' ) and schoolid not in (999999, 43) and grade_level <> 13 and Enroll_Status in (0,-1) AND LENGTH(s_sc_stu_contacts_x.cnt10_wphone) = 2);


 --Parent name blank, relationship not blank
 select  (select ABBREVIATION from SCHOOLS where students.SCHOOLID=SCHOOL_NUMBER) as School, 'Contact 2' as "Error Location", 'Parent name field blank' as Error, students.LASTFIRST, students.STUDENT_NUMBER, cnt2_rel, cnt2_fname, cnt2_lname from  s_sc_stu_contacts_x inner join students on s_sc_stu_contacts_x.studentsdcid=students.dcid where cnt2_rel is not null and (cnt2_lname is null OR cnt2_fname is null) and schoolid <> '999999' and grade_level <> 13 and Enroll_Status in (0,-1) order by 1, 3 ;
 select  (select ABBREVIATION from SCHOOLS where students.SCHOOLID=SCHOOL_NUMBER) as School, 'Contact 3' as "Error Location", 'Parent name field blank' as Error, students.LASTFIRST, students.STUDENT_NUMBER, cnt3_rel, cnt3_fname, cnt3_lname from  s_sc_stu_contacts_x inner join students on s_sc_stu_contacts_x.studentsdcid=students.dcid where cnt3_rel is not null and (cnt3_lname is null OR cnt3_fname is null) and schoolid <> '999999' and grade_level <> 13 and Enroll_Status in (0,-1) order by 1, 3 ;
 select  (select ABBREVIATION from SCHOOLS where students.SCHOOLID=SCHOOL_NUMBER) as School, 'Contact 4' as "Error Location", 'Parent name field blank' as Error, students.LASTFIRST, students.STUDENT_NUMBER, cnt4_rel, cnt4_fname, cnt4_lname from  s_sc_stu_contacts_x inner join students on s_sc_stu_contacts_x.studentsdcid=students.dcid where cnt4_rel is not null and (cnt4_lname is null OR cnt4_fname is null) and schoolid <> '999999' and grade_level <> 13 and Enroll_Status in (0,-1) order by 1, 3 ;
 select  (select ABBREVIATION from SCHOOLS where students.SCHOOLID=SCHOOL_NUMBER) as School, 'Contact 5' as "Error Location", 'Parent name field blank' as Error, students.LASTFIRST, students.STUDENT_NUMBER, cnt5_rel, cnt5_fname, cnt5_lname from  s_sc_stu_contacts_x inner join students on s_sc_stu_contacts_x.studentsdcid=students.dcid where cnt5_rel is not null and (cnt5_lname is null OR cnt5_fname is null) and schoolid <> '999999' and grade_level <> 13 and Enroll_Status in (0,-1) order by 1, 3 ;
 select  (select ABBREVIATION from SCHOOLS where students.SCHOOLID=SCHOOL_NUMBER) as School, 'Contact 6' as "Error Location", 'Parent name field blank' as Error, students.LASTFIRST, students.STUDENT_NUMBER, cnt6_rel, cnt6_fname, cnt6_lname from  s_sc_stu_contacts_x inner join students on s_sc_stu_contacts_x.studentsdcid=students.dcid where cnt6_rel is not null and (cnt6_lname is null OR cnt6_fname is null) and schoolid <> '999999' and grade_level <> 13 and Enroll_Status in (0,-1) order by 1, 3 ; 
 select  (select ABBREVIATION from SCHOOLS where students.SCHOOLID=SCHOOL_NUMBER) as School, 'Contact 7' as "Error Location", 'Parent name field blank' as Error, students.LASTFIRST, students.STUDENT_NUMBER, cnt7_rel, cnt7_fname, cnt7_lname from  s_sc_stu_contacts_x inner join students on s_sc_stu_contacts_x.studentsdcid=students.dcid where cnt7_rel is not null and (cnt7_lname is null OR cnt7_fname is null) and schoolid <> '999999' and grade_level <> 13 and Enroll_Status in (0,-1) order by 1, 3 ;
 select  (select ABBREVIATION from SCHOOLS where students.SCHOOLID=SCHOOL_NUMBER) as School, 'Contact 8' as "Error Location", 'Parent name field blank' as Error, students.LASTFIRST, students.STUDENT_NUMBER, cnt8_rel, cnt8_fname, cnt8_lname from  s_sc_stu_contacts_x inner join students on s_sc_stu_contacts_x.studentsdcid=students.dcid where cnt8_rel is not null and (cnt8_lname is null OR cnt8_fname is null) and schoolid <> '999999' and grade_level <> 13 and Enroll_Status in (0,-1) order by 1, 3 ;
 select  (select ABBREVIATION from SCHOOLS where students.SCHOOLID=SCHOOL_NUMBER) as School, 'Contact 9' as "Error Location", 'Parent name field blank' as Error, students.LASTFIRST, students.STUDENT_NUMBER, cnt9_rel, cnt9_fname, cnt9_lname from  s_sc_stu_contacts_x inner join students on s_sc_stu_contacts_x.studentsdcid=students.dcid where cnt9_rel is not null and (cnt9_lname is null OR cnt9_fname is null) and schoolid <> '999999' and grade_level <> 13 and Enroll_Status in (0,-1) order by 1, 3 ;
 select  (select ABBREVIATION from SCHOOLS where students.SCHOOLID=SCHOOL_NUMBER) as School, 'Contact 10' as "Error Location", 'Parent name field blank' as Error, students.LASTFIRST, students.STUDENT_NUMBER, cnt10_rel, cnt10_fname, cnt10_lname from  s_sc_stu_contacts_x inner join students on s_sc_stu_contacts_x.studentsdcid=students.dcid where cnt10_rel is not null and (cnt10_lname is null OR cnt10_fname is null) and schoolid <> '999999' and grade_level <> 13 and Enroll_Status in (0,-1) order by 1, 3 ;

