SELECT 
  to_char (STUDENTS.STUDENT_NUMBER) StudentID,
  STUDENTS.LASTFIRST Name,
  (select ABBREVIATION from SCHOOLS where REENROLLMENTS.SCHOOLID=SCHOOL_NUMBER) MS,
  REENROLLMENTS.SCHOOLID "MS School ID",
  Reenrollments.GRADE_LEVEL "MS Grade",
  TO_CHAR(REENROLLMENTS.ENTRYDATE,'MM/DD/YY') "MS Entry Date",
  TO_CHAR(REENROLLMENTS.EXITDATE,'MM/DD/YY') "MS Exit Date"
FROM STUDENTS
JOIN REENROLLMENTS
ON STUDENTS.ID = REENROLLMENTS.STUDENTID
WHERE STUDENTS.SCHOOLID = 69
and enroll_status = 0
and reenrollments.grade_level in (6, 7, 8)
order by lastfirst
;
select * from reenrollments

