SELECT PS.STUDENTS.STUDENT_NUMBER,
  PS.STUDENTS.LASTFIRST,
  PS.STUDENTS.GRADE_LEVEL,
  PS.CC.COURSE_NUMBER,
  PS.CC.SECTION_NUMBER,
  PS.COURSES.COURSE_NAME,
  TEACHERS.LASTFIRST AS TEACHERNAME,
  
  DECODE(CNTA1_CUSTODY,1,CNT1_FNAME || ' ' || CNT1_LNAME,
    DECODE(CNT2_CUSTODY,1,CNT2_FNAME || ' ' || CNT2_LNAME,
      DECODE(CNT3_CUSTODY,1,CNT3_FNAME || ' ' || CNT3_LNAME,
        DECODE(CNT4_CUSTODY,1,CNT4_FNAME || ' ' || CNT4_LNAME,
          DECODE(CNT5_CUSTODY,1,CNT5_FNAME || ' ' || CNT5_LNAME,
            DECODE(CNT6_CUSTODY,1,CNT6_FNAME || ' ' || CNT6_LNAME,
              DECODE(CNT7_CUSTODY,1,CNT7_FNAME || ' ' || CNT7_LNAME,
                DECODE(CNT8_CUSTODY,1,CNT8_FNAME || ' ' || CNT8_LNAME,
                  DECODE(CNT9_CUSTODY,1,CNT9_FNAME || ' ' || CNT9_LNAME,
                    DECODE(CNT10_CUSTODY,1,CNT10_FNAME || ' ' || CNT10_LNAME,
  NULL)))))))))) Guardian
  
FROM PS.STUDENTS
INNER JOIN PS.CC
ON PS.STUDENTS.ID = PS.CC.STUDENTID
INNER JOIN SECTIONS
ON SECTIONS.ID = PS.CC.SECTIONID
INNER JOIN TEACHERS
ON TEACHERS.ID = CC.TEACHERID
INNER JOIN PS.COURSES
ON PS.COURSES.COURSE_NUMBER = SECTIONS.COURSE_NUMBER
INNER JOIN PS.S_SC_STU_X
ON PS.S_SC_STU_X.STUDENTSDCID = PS.STUDENTS.DCID
INNER JOIN PS.S_SC_STU_CONTACTS_X
ON PS.STUDENTS.DCID             = PS.S_SC_STU_CONTACTS_X.STUDENTSDCID
WHERE PS.STUDENTS.ENROLL_STATUS = 0
AND PS.CC.TERMID LIKE '30%'
