SELECT TO_CHAR(students.STUDENT_NUMBER),
  PS.STUDENTS.FIRST_NAME,
  PS.STUDENTS.LAST_NAME AS LAST_NAME1,
  PS.STUDENTS.DOB,
  PS.STUDENTS.GENDER,
  DECODE(PS.STUDENTS.ETHNICITY, 'I', 'American Indian or Alaska Native', 'A', 'Asian, Asian American', 'B', 'Black or African American', 'H', 'Hispanic', 'P', 'Native Hawaiian or Other Pacific Islander', 'W', 'White', 'M', 'Two or More Races'),
  PS.STUDENTS.GRADE_LEVEL,
  decode(PS.STUDENTS.LUNCHSTATUS,'F','Y','R','Y','P','N'),
  DECODE(PS.S_SC_STU_X.PARENTSMILITARYSTATUS, 1, 'Y', 2, 'Y', 5, 'Y', 6, 'Y', 8, 'Y',null,'N'),
  PS.CC.COURSE_NUMBER,
  PS.COURSES.COURSE_NAME,
  TEACHERS.ID,
  TEACHERS.FIRST_NAME,
  TEACHERS.LAST_NAME,
  TEACHERS.EMAIL_ADDR,
  PS.CC.EXPRESSION,
  decode(PS.CC.TERMID,2800,'All Year',2801,'Semester 1',2802,'Semester 2')
FROM PS.STUDENTS
INNER JOIN PS.CC
ON PS.STUDENTS.ID = PS.CC.STUDENTID
INNER JOIN SECTIONS
ON SECTIONS.ID = PS.CC.SECTIONID
INNER JOIN TEACHERS
ON TEACHERS.ID = SECTIONS.TEACHER
INNER JOIN PS.COURSES
ON PS.COURSES.COURSE_NUMBER = SECTIONS.COURSE_NUMBER
INNER JOIN PS.S_SC_STU_X
ON PS.S_SC_STU_X.STUDENTSDCID = PS.STUDENTS.DCID
WHERE PS.CC.TERMID LIKE '28%'
AND PS.STUDENTS.ENROLL_STATUS = 0
AND PS.STUDENTS.SCHOOLID      = 100
AND (PS.COURSES.COURSE_NUMBER LIKE '%AW'
OR PS.COURSES.COURSE_NUMBER LIKE '%AH')
ORDER BY PS.STUDENTS.LASTFIRST