SELECT S.STUDENT_NUMBER AS "Student ID",
  S.LASTFIRST           AS "Student Name",
  S.GRADE_LEVEL         AS GR,
  SE.COURSE_NUMBER      AS "Course #",
  C.COURSE_NAME         AS "Course Name",
  SG.EARNEDCRHRS AS Credit,
  SC.PECOMPCODE AS "PE Code"
FROM STUDENTS S,
  COURSES C,
  TEACHERS T,
  SECTIONS SE,
  STOREDGRADES SG,
  S_SC_STU_X SC
WHERE S.ID           = SG.STUDENTID
AND SE.ID            = SG.SECTIONID
AND C.COURSE_NUMBER  = SE.COURSE_NUMBER
AND T.ID             = SE.TEACHER
AND SC.STUDENTSDCID=S.DCID
AND SG.STORECODE     = 'F1'
AND SG.GRADE         > '60'
AND SG.EARNEDCRHRS   > '0'
AND S.SCHOOLID       = 100
AND S.ENROLL_STATUS  = 0
AND (C.COURSE_NUMBER = '344100CW'
OR C.COURSE_NUMBER = '344200CW')
ORDER BY
  "Student Name",
  "Course Name"