SELECT
  (SELECT SCHOOLS.ABBREVIATION
  FROM SCHOOLS
  WHERE STUDENTS.SCHOOLID = SCHOOLS.SCHOOL_NUMBER
  ) SchoolAbrev,
  DECODE(Grouping(U_STUDENTSUSERFIELDS.R_PROOF_OF_RESIDENCY), 1, 'Total', U_STUDENTSUSERFIELDS.R_PROOF_OF_RESIDENCY) AS Value,
  COUNT(1)
FROM STUDENTS
INNER JOIN U_STUDENTSUSERFIELDS
ON STUDENTS.DCID                                      = U_STUDENTSUSERFIELDS.STUDENTSDCID
WHERE (U_STUDENTSUSERFIELDS.R_PROOF_OF_RESIDENCY NOT IN ('C', 'H', '2'))
OR (U_STUDENTSUSERFIELDS.R_PROOF_OF_RESIDENCY        IS NULL
AND STUDENTS.ENROLL_STATUS                            = 0
AND STUDENTS.SCHOOLID NOT                            IN ('43', '999999'))
GROUP BY ROLLUP(STUDENTS.SCHOOLID, U_STUDENTSUSERFIELDS.R_PROOF_OF_RESIDENCY)
ORDER BY STUDENTS.SCHOOLID,
  U_STUDENTSUSERFIELDS.R_PROOF_OF_RESIDENCY NULLS LAST