SELECT CNT1_REL FROM S_SC_STU_CONTACTS_X
UNION
SELECT CNT2_REL FROM S_SC_STU_CONTACTS_X
UNION
SELECT CNT3_REL FROM S_SC_STU_CONTACTS_X
UNION
SELECT CNT4_REL FROM S_SC_STU_CONTACTS_X
UNION
SELECT CNT5_REL FROM S_SC_STU_CONTACTS_X
UNION
SELECT CNT6_REL FROM S_SC_STU_CONTACTS_X
UNION
SELECT CNT7_REL FROM S_SC_STU_CONTACTS_X
UNION
SELECT CNT8_REL FROM S_SC_STU_CONTACTS_X
UNION
SELECT CNT9_REL FROM S_SC_STU_CONTACTS_X
UNION
SELECT CNT10_REL FROM S_SC_STU_CONTACTS_X
ORDER BY 1 ASC