SELECT
  STUDENTS.LASTFIRST,
  STUDENTS.STUDENT_NUMBER,
  STUDENTS.GRADE_LEVEL,
  STUDENTS.GENDER,
  PS.CC.COURSE_NUMBER
FROM
  STUDENTS
INNER JOIN PS.CC
ON
  STUDENTS.ID = PS.CC.SECTIONID,
  PS.S_SC_STU_X
WHERE
  STUDENTS.GRADE_LEVEL  = 9
AND STUDENTS.GENDER     = 'F'
AND STUDENTS.SCHOOLID   = 100
AND PS.CC.COURSE_NUMBER = '08960000'
ORDER BY
  STUDENTS.STUDENT_NUMBER,
  STUDENTS.LASTFIRST DESC