SELECT PS.STOREDGRADES.TERMID,
  PS.STOREDGRADES.STORECODE,
  PS.STOREDGRADES.SCHOOLNAME,
  PS.STUDENTS.SCHOOLID,
  PS.STUDENTS.STUDENT_NUMBER,
  PS.STUDENTS.LASTFIRST
FROM PS.STOREDGRADES
INNER JOIN PS.STUDENTS
ON PS.STOREDGRADES.STUDENTID  = PS.STUDENTS.ID
where PS.STOREDGRADES.TERMID IN (2500, 2501, 2502)
AND PS.STUDENTS.SCHOOLID      = 100