SELECT 
TO_CHAR(Students.STUDENT_NUMBER),
  STUDENTS.LASTFIRST,
  STUDENTS.GRADE_LEVEL,
  SECTIONS.COURSE_NUMBER,
  COURSES.COURSE_NAME,
  SECTIONS.TERMID,
  Teachers.LASTFIRST AS LASTFIRST1
FROM STUDENTS,
  CC,
  SECTIONS,
  Teachers,
  COURSES
WHERE STUDENTS.ID         = CC.STUDENTID
AND SECTIONS.ID           = CC.SECTIONID
AND Teachers.ID           = SECTIONS.TEACHER
AND COURSES.COURSE_NUMBER = SECTIONS.COURSE_NUMBER
AND SECTIONS.COURSE_NUMBER LIKE '32210%'
AND SECTIONS.TERMID        = '2802'
AND STUDENTS.SCHOOLID      = 100
AND STUDENTS.ENROLL_STATUS = '0'