SELECT PS.STOREDGRADES.TERMID,
  PS.STOREDGRADES.STORECODE,
  PS.STOREDGRADES.SCHOOLNAME,
  PS.STUDENTS.SCHOOLID,
  PS.STUDENTS.STUDENT_NUMBER,
  PS.STUDENTS.LASTFIRST,
  PS.STUDENTS.GRADE_LEVEL,
  PS.S_SC_STU_X.advisor
FROM PS.STOREDGRADES
INNER JOIN PS.STUDENTS
ON PS.STOREDGRADES.STUDENTID = PS.STUDENTS.ID
INNER JOIN PS.S_SC_STU_X
ON PS.S_SC_STU_X.STUDENTSDCID = PS.STUDENTS.DCID
WHERE PS.STOREDGRADES.TERMID LIKE '26%'
AND PS.STOREDGRADES.SCHOOLNAME = 'Westwood High School- Virtualsc Online'
AND PS.STUDENTS.SCHOOLID       = 100
AND PS.STUDENTS.GRADE_LEVEL    < 12